title: "The Universal Dev"
description: "The Universal Dev - Teaching the world code and design through blog posts, and easy-to-follow tutorial videos on YouTube."
author: The Universal Dev
baseurl: ""
